In [27]:
import pandas as pd
import requests

response=requests.get ('http://www.omdbapi.com/?i=tt3896198&apikey=c2a4403b')
response.json()

{'Title': 'Guardians of the Galaxy Vol. 2',
 'Year': '2017',
 'Rated': 'PG-13',
 'Released': '05 May 2017',
 'Runtime': '136 min',
 'Genre': 'Action, Adventure, Comedy',
 'Director': 'James Gunn',
 'Writer': 'James Gunn, Dan Abnett, Andy Lanning',
 'Actors': 'Chris Pratt, Zoe Saldaña, Dave Bautista',
 'Plot': "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
 'Language': 'English',
 'Country': 'United States',
 'Awards': 'Nominated for 1 Oscar. 15 wins & 60 nominations total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWE5MGI3MDctMmU5Ni00YzI2LWEzMTQtZGIyZDA5MzQzNDBhXkEyXkFqcGc@._V1_SX300.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '85%'},
  {'Source': 'Metacritic', 'Value': '67/100'}],
 'Metascore': '67',
 'imdbRating': '7.6',
 'imdbVotes': '823,054',
 'imdbID': 'tt3896198',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$389,813,101',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [12]:
response.json()

{'Title': 'Guardians of the Galaxy Vol. 2',
 'Year': '2017',
 'Rated': 'PG-13',
 'Released': '05 May 2017',
 'Runtime': '136 min',
 'Genre': 'Action, Adventure, Comedy',
 'Director': 'James Gunn',
 'Writer': 'James Gunn, Dan Abnett, Andy Lanning',
 'Actors': 'Chris Pratt, Zoe Saldaña, Dave Bautista',
 'Plot': "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
 'Language': 'English',
 'Country': 'United States',
 'Awards': 'Nominated for 1 Oscar. 15 wins & 60 nominations total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNWE5MGI3MDctMmU5Ni00YzI2LWEzMTQtZGIyZDA5MzQzNDBhXkEyXkFqcGc@._V1_SX300.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '85%'},
  {'Source': 'Metacritic', 'Value': '67/100'}],
 'Metascore': '67',
 'imdbRating': '7.6',
 'imdbVotes': '823,054',
 'imdbID': 'tt3896198',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$389,813,101',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [17]:
data=response.json()
temp_df=pd.DataFrame(['data'])

In [15]:
temp_df

      0
0  data

In [18]:
print(type(data))

<class 'dict'>

In [19]:
temp_df = pd.DataFrame([data])
print(temp_df.head())

                            Title  Year  Rated     Released  Runtime  \
0  Guardians of the Galaxy Vol. 2  2017  PG-13  05 May 2017  136 min

                       Genre    Director  \
0  Action, Adventure, Comedy  James Gunn

                                 Writer  \
0  James Gunn, Dan Abnett, Andy Lanning

                                    Actors  \
0  Chris Pratt, Zoe Saldaña, Dave Bautista

                                                Plot  ... Metascore  \
0  The Guardians struggle to keep together as a t...  ...        67

  imdbRating imdbVotes     imdbID   Type  DVD     BoxOffice Production  \
0        7.6   823,054  tt3896198  movie  N/A  $389,813,101        N/A

  Website Response
0     N/A     True

[1 rows x 25 columns]

In [24]:
df=temp_df[['Title','Year','Rated','Writer','Actors']]

In [25]:
df

,Title,Year,Rated,Writer,Actors
0,Guardians of the Galaxy Vol. 2,2017,PG-13,"James Gunn, Dan Abnett, Andy Lanning","Chris Pratt, Zoe Saldaña, Dave Bautista"

In [32]:
import pandas as pd
import requests

response=requests.get('https://api.nasa.gov/insight_weather/?api_key=Qe2MWBxfDNfufpfiMPeCgnOE0l2KONx1a8DJpTpc&feedtype=json&ver=1.0')
data=response.json()

In [33]:
data

{'675': {'AT': {'av': -62.314, 'ct': 177556, 'mn': -96.872, 'mx': -15.908},
  'First_UTC': '2020-10-19T18:32:20Z',
  'HWS': {'av': 7.233, 'ct': 88628, 'mn': 1.051, 'mx': 22.455},
  'Last_UTC': '2020-10-20T19:11:55Z',
  'Month_ordinal': 10,
  'Northern_season': 'early winter',
  'PRE': {'av': 750.563, 'ct': 887776, 'mn': 722.0901, 'mx': 768.791},
  'Season': 'fall',
  'Southern_season': 'early summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 254},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 1},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 8618},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 1912},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 19517},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 30283},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 25962},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 2014},
   '9': {'compass_degrees': 202.5,
    'compass_point': 'SSW',
    'compass_right': -0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 67},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 30283}}},
 '676': {'AT': {'av': -62.812, 'ct': 177554, 'mn': -96.912, 'mx': -16.499},
  'First_UTC': '2020-10-20T19:11:55Z',
  'HWS': {'av': 8.526, 'ct': 88250, 'mn': 1.11, 'mx': 26.905},
  'Last_UTC': '2020-10-21T19:51:31Z',
  'Month_ordinal': 10,
  'Northern_season': 'early winter',
  'PRE': {'av': 749.09, 'ct': 887777, 'mn': 722.473, 'mx': 767.1426},
  'Season': 'fall',
  'Southern_season': 'early summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 463},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 45},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 2749},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 4862},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 20685},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 31167},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 25783},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 2490},
   '2': {'compass_degrees': 45.0,
    'compass_point': 'NE',
    'compass_right': 0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 4},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 2},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 31167}}},
 '677': {'AT': {'av': -63.056, 'ct': 177556, 'mn': -97.249, 'mx': -16.853},
  'First_UTC': '2020-10-21T19:51:31Z',
  'HWS': {'av': 7.887, 'ct': 88610, 'mn': 0.511, 'mx': 23.197},
  'Last_UTC': '2020-10-22T20:31:06Z',
  'Month_ordinal': 11,
  'Northern_season': 'mid winter',
  'PRE': {'av': 748.698, 'ct': 887776, 'mn': 720.5873, 'mx': 767.4249},
  'Season': 'fall',
  'Southern_season': 'mid summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 511},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 12},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 3083},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 3370},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 19454},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 34749},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 24014},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 3413},
   '2': {'compass_degrees': 45.0,
    'compass_point': 'NE',
    'compass_right': 0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 1},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 3},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 34749}}},
 '678': {'AT': {'av': -62.562, 'ct': 177556, 'mn': -97.728, 'mx': -9.055},
  'First_UTC': '2020-10-22T20:31:06Z',
  'HWS': {'av': 5.246, 'ct': 86963, 'mn': 0.244, 'mx': 18.399},
  'Last_UTC': '2020-10-23T21:10:41Z',
  'Month_ordinal': 11,
  'Northern_season': 'mid winter',
  'PRE': {'av': 743.741, 'ct': 887777, 'mn': 717.7254, 'mx': 760.2834},
  'Season': 'fall',
  'Southern_season': 'mid summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 2680},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 1025},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 10492},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 3499},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 22094},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 26617},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 14104},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 4388},
   '2': {'compass_degrees': 45.0,
    'compass_point': 'NE',
    'compass_right': 0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 305},
   '3': {'compass_degrees': 67.5,
    'compass_point': 'ENE',
    'compass_right': 0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 31},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 211},
   '6': {'compass_degrees': 135.0,
    'compass_point': 'SE',
    'compass_right': 0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 45},
   '7': {'compass_degrees': 157.5,
    'compass_point': 'SSE',
    'compass_right': 0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 174},
   '8': {'compass_degrees': 180.0,
    'compass_point': 'S',
    'compass_right': 0.0,
    'compass_up': -1.0,
    'ct': 437},
   '9': {'compass_degrees': 202.5,
    'compass_point': 'SSW',
    'compass_right': -0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 861},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 26617}}},
 '679': {'AT': {'av': -62.551, 'ct': 177554, 'mn': -96.644, 'mx': -11.561},
  'First_UTC': '2020-10-23T21:10:41Z',
  'HWS': {'av': 5.565, 'ct': 87171, 'mn': 0.231, 'mx': 19.409000000000002},
  'Last_UTC': '2020-10-24T21:50:16Z',
  'Month_ordinal': 11,
  'Northern_season': 'mid winter',
  'PRE': {'av': 744.529, 'ct': 887776, 'mn': 719.4178, 'mx': 763.2724},
  'Season': 'fall',
  'Southern_season': 'mid summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 2049},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 657},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 11924},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 1379},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 21329},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 28774},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 15570},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 3784},
   '2': {'compass_degrees': 45.0,
    'compass_point': 'NE',
    'compass_right': 0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 83},
   '3': {'compass_degrees': 67.5,
    'compass_point': 'ENE',
    'compass_right': 0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 17},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 138},
   '6': {'compass_degrees': 135.0,
    'compass_point': 'SE',
    'compass_right': 0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 11},
   '7': {'compass_degrees': 157.5,
    'compass_point': 'SSE',
    'compass_right': 0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 137},
   '8': {'compass_degrees': 180.0,
    'compass_point': 'S',
    'compass_right': 0.0,
    'compass_up': -1.0,
    'ct': 410},
   '9': {'compass_degrees': 202.5,
    'compass_point': 'SSW',
    'compass_right': -0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 909},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 28774}}},
 '680': {'AT': {'av': -61.789, 'ct': 168902, 'mn': -96.811, 'mx': -15.298},
  'First_UTC': '2020-10-24T21:50:16Z',
  'HWS': {'av': 6.517, 'ct': 88478, 'mn': 0.275, 'mx': 24.235},
  'Last_UTC': '2020-10-25T22:29:51Z',
  'Month_ordinal': 11,
  'Northern_season': 'mid winter',
  'PRE': {'av': 743.99, 'ct': 887767, 'mn': 717.1398, 'mx': 764.0093},
  'Season': 'fall',
  'Southern_season': 'mid summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 1033},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 133},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 6463},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 2556},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 21280},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 34787},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 18673},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 3262},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 10},
   '6': {'compass_degrees': 135.0,
    'compass_point': 'SE',
    'compass_right': 0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 6},
   '7': {'compass_degrees': 157.5,
    'compass_point': 'SSE',
    'compass_right': 0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 23},
   '8': {'compass_degrees': 180.0,
    'compass_point': 'S',
    'compass_right': 0.0,
    'compass_up': -1.0,
    'ct': 76},
   '9': {'compass_degrees': 202.5,
    'compass_point': 'SSW',
    'compass_right': -0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 176},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 34787}}},
 '681': {'AT': {'av': -62.434, 'ct': 88778, 'mn': -95.447, 'mx': -4.444},
  'First_UTC': '2020-10-25T22:29:51Z',
  'HWS': {'av': 5.632, 'ct': 87184, 'mn': 0.228, 'mx': 18.577},
  'Last_UTC': '2020-10-26T23:09:26Z',
  'Month_ordinal': 11,
  'Northern_season': 'mid winter',
  'PRE': {'av': 743.55, 'ct': 887777, 'mn': 718.463, 'mx': 760.2244},
  'Season': 'fall',
  'Southern_season': 'mid summer',
  'WD': {'0': {'compass_degrees': 0.0,
    'compass_point': 'N',
    'compass_right': 0.0,
    'compass_up': 1.0,
    'ct': 1872},
   '1': {'compass_degrees': 22.5,
    'compass_point': 'NNE',
    'compass_right': 0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 881},
   '10': {'compass_degrees': 225.0,
    'compass_point': 'SW',
    'compass_right': -0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 12182},
   '11': {'compass_degrees': 247.5,
    'compass_point': 'WSW',
    'compass_right': -0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 1249},
   '12': {'compass_degrees': 270.0,
    'compass_point': 'W',
    'compass_right': -1.0,
    'compass_up': -0.0,
    'ct': 22409},
   '13': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 27816},
   '14': {'compass_degrees': 315.0,
    'compass_point': 'NW',
    'compass_right': -0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 15971},
   '15': {'compass_degrees': 337.5,
    'compass_point': 'NNW',
    'compass_right': -0.382683432365,
    'compass_up': 0.923879532511,
    'ct': 3412},
   '2': {'compass_degrees': 45.0,
    'compass_point': 'NE',
    'compass_right': 0.707106781187,
    'compass_up': 0.707106781187,
    'ct': 201},
   '3': {'compass_degrees': 67.5,
    'compass_point': 'ENE',
    'compass_right': 0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 57},
   '5': {'compass_degrees': 112.5,
    'compass_point': 'ESE',
    'compass_right': 0.923879532511,
    'compass_up': -0.382683432365,
    'ct': 129},
   '6': {'compass_degrees': 135.0,
    'compass_point': 'SE',
    'compass_right': 0.707106781187,
    'compass_up': -0.707106781187,
    'ct': 17},
   '7': {'compass_degrees': 157.5,
    'compass_point': 'SSE',
    'compass_right': 0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 112},
   '8': {'compass_degrees': 180.0,
    'compass_point': 'S',
    'compass_right': 0.0,
    'compass_up': -1.0,
    'ct': 387},
   '9': {'compass_degrees': 202.5,
    'compass_point': 'SSW',
    'compass_right': -0.382683432365,
    'compass_up': -0.923879532511,
    'ct': 489},
   'most_common': {'compass_degrees': 292.5,
    'compass_point': 'WNW',
    'compass_right': -0.923879532511,
    'compass_up': 0.382683432365,
    'ct': 27816}}},
 'sol_keys': ['675', '676', '677', '678', '679', '680', '681'],
 'validity_checks': {'674': {'AT': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'HWS': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'PRE': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'WD': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True}},
  '675': {'AT': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'HWS': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'PRE': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'WD': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True}},
  '676': {'AT': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'HWS': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'PRE': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True},
   'WD': {'sol_hours_with_data': [0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23],
    'valid': True}},
  '677': {'AT': {'sol_hours_with_data': [0,

In [35]:
print(type(data))

<class 'dict'>

In [37]:
df=pd.DataFrame(['data'])

In [38]:
df

      0
0  data

In [39]:
temp_df1 = pd.DataFrame([data])
print(temp_df1.head())

                                                 675  \
0  {'AT': {'av': -62.314, 'ct': 177556, 'mn': -96...

                                                 676  \
0  {'AT': {'av': -62.812, 'ct': 177554, 'mn': -96...

                                                 677  \
0  {'AT': {'av': -63.056, 'ct': 177556, 'mn': -97...

                                                 678  \
0  {'AT': {'av': -62.562, 'ct': 177556, 'mn': -97...

                                                 679  \
0  {'AT': {'av': -62.551, 'ct': 177554, 'mn': -96...

                                                 680  \
0  {'AT': {'av': -61.789, 'ct': 168902, 'mn': -96...

                                                 681  \
0  {'AT': {'av': -62.434, 'ct': 88778, 'mn': -95....

                              sol_keys  \
0  [675, 676, 677, 678, 679, 680, 681]

                                     validity_checks
0  {'674': {'AT': {'sol_hours_with_data': [0, 1, ...

In [41]:
temp_df1

,675,676,677,678,679,680,681,sol_keys,validity_checks
0,"{'AT': {'av': -62.314, 'ct': 177556, 'mn': -96...","{'AT': {'av': -62.812, 'ct': 177554, 'mn': -96...","{'AT': {'av': -63.056, 'ct': 177556, 'mn': -97...","{'AT': {'av': -62.562, 'ct': 177556, 'mn': -97...","{'AT': {'av': -62.551, 'ct': 177554, 'mn': -96...","{'AT': {'av': -61.789, 'ct': 168902, 'mn': -96...","{'AT': {'av': -62.434, 'ct': 88778, 'mn': -95....","[675, 676, 677, 678, 679, 680, 681]","{'674': {'AT': {'sol_hours_with_data': [0, 1, ..."