In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [2]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get("https://books.toscrape.com/catalogue/page-1.html",headers=headers).text

In [3]:
soup=BeautifulSoup(webpage,'lxml')

In [4]:
Books=soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [5]:
name=[]
price=[]
availability=[]


for i in Books:
    name.append(i.find('h3').text.strip())
    price.append(i.find("p",class_='price_color').text.strip())
    availability.append(i.find('p',class_="instock availability").text.strip())

In [6]:
d={'name':name,'price':price,'availability':availability}
df=pd.DataFrame(d)

In [7]:
df

                                     name    price availability
0                      A Light in the ...  Â£51.77     In stock
1                      Tipping the Velvet  Â£53.74     In stock
2                              Soumission  Â£50.10     In stock
3                           Sharp Objects  Â£47.82     In stock
4            Sapiens: A Brief History ...  Â£54.23     In stock
5                         The Requiem Red  Â£22.65     In stock
6            The Dirty Little Secrets ...  Â£33.34     In stock
7                 The Coming Woman: A ...  Â£17.93     In stock
8                     The Boys in the ...  Â£22.60     In stock
9                         The Black Maria  Â£52.15     In stock
10  Starving Hearts (Triangular Trade ...  Â£13.99     In stock
11                  Shakespeare's Sonnets  Â£20.66     In stock
12                            Set Me Free  Â£17.46     In stock
13    Scott Pilgrim's Precious Little ...  Â£52.29     In stock
14                      Rip it Up and ...  Â£35.02     In stock
15                  Our Band Could Be ...  Â£57.25     In stock
16                                   Olio  Â£23.88     In stock
17        Mesaerion: The Best Science ...  Â£37.59     In stock
18           Libertarianism for Beginners  Â£51.33     In stock
19                It's Only the Himalayas  Â£45.17     In stock

In [8]:
# Accessing Multiple Pages or All Pages

final=pd.DataFrame()

for j in range(1,100):
    url="https://books.toscrape.com/catalogue/page-{}.html".format(j)
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage=requests.get(url,headers=headers).text

    soup=BeautifulSoup(webpage,'lxml')
    Books=soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

    
    name=[]
    price=[]
    availability=[]
    
    
    for i in Books:
        name.append(i.find('h3').text.strip())
        price.append(i.find("p",class_='price_color').text.strip())
        availability.append(i.find('p',class_="instock availability").text.strip())
    

    d={'name':name,'price':price,'availability':availability}
    df=pd.DataFrame(d)



    final = pd.concat([final,df],ignore_index=True)

In [9]:
final

                                 name    price availability
0                  A Light in the ...  Â£51.77     In stock
1                  Tipping the Velvet  Â£53.74     In stock
2                          Soumission  Â£50.10     In stock
3                       Sharp Objects  Â£47.82     In stock
4        Sapiens: A Brief History ...  Â£54.23     In stock
..                                ...      ...          ...
995  Alice in Wonderland (Alice's ...  Â£55.53     In stock
996    Ajin: Demi-Human, Volume 1 ...  Â£57.06     In stock
997         A Spy's Devotion (The ...  Â£16.97     In stock
998           1st to Die (Women's ...  Â£53.98     In stock
999           1,000 Places to See ...  Â£26.08     In stock

[1000 rows x 3 columns]

In [10]:
final.shape

(1000, 3)

In [11]:
final.isnull().sum()

name            0
price           0
availability    0
dtype: int64

In [12]:
# Cleaned Data

In [14]:
final.to_csv('Books_dataset.csv',index=False)